# Generated by Django 3.0 on 2020-02-10 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='decsription',
            field=models.TextField(default='Project lalalalla ayeiuahwjanwkja wjabkwjhawh awh awh ajkwh akjwh ahw kawk ahkwh ajwkha jkwhakj hwakj hwkja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Open', max_length=50),
            preserve_default=False,
        ),
    ]
